# .github/workflows/deploy.yml
name: Deploy Angular App to GitHub Pages Ashish

on:
  push:
    branches: [ "main" ] # Trigger on push to main branch
  workflow_dispatch: # Allows manual trigger from Actions tab

permissions:
  contents: read # Allow reading repository content
  pages: write   # Allow writing to the GitHub Pages deployment
  id-token: write # Allow authentication with GitHub OIDC Token

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # The URL of the deployed site

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use your preferred Node.js version

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular Application
        # Build your Angular app. 'outputPath' in angular.json is 'dist/care-monitor-demo'
        # Use --base-href for routing if not configured in angular.json already
        run: npm run build --configuration production --base-href=/careMonitorDemo/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/care-monitor-demo/browser # Path to your built Angular app

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # This action requires the 'pages' permission in the workflow and the 'Deploy from a branch' setting.
